USE master;
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'QL_BENHVIEN')
BEGIN
    ALTER DATABASE QL_BENHVIEN SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE QL_BENHVIEN;
END
GO

CREATE DATABASE QL_BENHVIEN;
GO

USE QL_BENHVIEN;
GO

-- ==========================================
-- TẠO BẢNG
-- ==========================================

-- 1. Table BENHVIEN
CREATE TABLE BENHVIEN (
    BENHVIEN_ID INT IDENTITY(1,1) PRIMARY KEY,
    MABENHVIEN AS ('BV' + RIGHT('00' + CAST(BENHVIEN_ID AS VARCHAR(3)), 2)) PERSISTED,
    TENBENHVIEN NVARCHAR(100),
    SDT VARCHAR(15),
    DIACHI NVARCHAR(200)
);

-- 2. Table KHOA
CREATE TABLE KHOA (
    KHOA_ID INT IDENTITY(1,1) PRIMARY KEY,
    MAKHOA AS ('K' + RIGHT('000' + CAST(KHOA_ID AS VARCHAR(4)), 3)) PERSISTED,
    TENKHOA NVARCHAR(100),
    BENHVIEN_ID INT,
    SOBS INT,
    CONSTRAINT FK_KHOA_BENHVIEN FOREIGN KEY (BENHVIEN_ID) REFERENCES BENHVIEN(BENHVIEN_ID) ON DELETE CASCADE
);

-- 3. Table BACSI
CREATE TABLE BACSI (
    BACSI_ID INT IDENTITY(1,1) PRIMARY KEY,
    MABACSI AS ('BS' + RIGHT('000' + CAST(BACSI_ID AS VARCHAR(4)), 3)) PERSISTED,
    TENBACSI NVARCHAR(100),
    GIOITINH NVARCHAR(10),
    NAMSINH INT,
    KHOA_ID INT,
    SOBN INT,
    HOCHAM NVARCHAR(20),
    HOCVI NVARCHAR(50),
    CHUCVU NVARCHAR(50),
    AVATAR NVARCHAR(200),
    CONSTRAINT FK_BACSI_KHOA FOREIGN KEY (KHOA_ID) REFERENCES KHOA(KHOA_ID) ON DELETE CASCADE
);

-- 4. Table BENHNHAN
CREATE TABLE BENHNHAN (
    BNHAN_ID INT IDENTITY(1,1) PRIMARY KEY,
    MABENHNHAN AS ('BN' + RIGHT('000' + CAST(BNHAN_ID AS VARCHAR(4)), 3)) PERSISTED,
    HOTENBENHNHAN NVARCHAR(100),
    SDT VARCHAR(15),
    GIOITINH NVARCHAR(10),
    BACSI_ID INT,
    AVATAR NVARCHAR(200),
    CCCD VARCHAR(12),
    CONSTRAINT FK_BENHNHAN_BACSI FOREIGN KEY (BACSI_ID) REFERENCES BACSI(BACSI_ID)
);

-- 5. Table CAKHAM_MAPPING
CREATE TABLE CAKHAM_MAPPING (
    CAKHAM_ID INT PRIMARY KEY,
    GIOKHAM TIME(7)
);

-- 6. Table DATLICHKHAM
CREATE TABLE DATLICHKHAM (
    DATLICHKHAM_ID INT IDENTITY(1,1) PRIMARY KEY,
    BNHAN_ID INT,
    BACSI_ID INT,
    NGAYKHAM DATE,
    CAKHAM_ID INT,
    TRANGTHAI NVARCHAR(50),
    THOIGIANDAT DATETIME,
    CONSTRAINT FK_DATLICH_BENHNHAN FOREIGN KEY (BNHAN_ID) REFERENCES BENHNHAN(BNHAN_ID) ON DELETE CASCADE,
    CONSTRAINT FK_DATLICH_BACSI FOREIGN KEY (BACSI_ID) REFERENCES BACSI(BACSI_ID),
    CONSTRAINT FK_DATLICH_CAKHAM FOREIGN KEY (CAKHAM_ID) REFERENCES CAKHAM_MAPPING(CAKHAM_ID)
);

-- 7. Table DICHVU
CREATE TABLE DICHVU (
    DV_ID INT IDENTITY(1,1) PRIMARY KEY,
    MADV AS ('DV' + RIGHT('000' + CAST(DV_ID AS VARCHAR(4)), 3)) PERSISTED,
    TENDV NVARCHAR(100),
    DONGIA DECIMAL(18,2),
    GHICHU NVARCHAR(200),
    KHOA_ID INT,
    CONSTRAINT FK_DICHVU_KHOA FOREIGN KEY (KHOA_ID) REFERENCES KHOA(KHOA_ID) ON DELETE CASCADE
);

-- 8. Table HOADON
CREATE TABLE HOADON (
    HD_ID INT IDENTITY(1,1) PRIMARY KEY,
    MAHD AS ('HD' + RIGHT('000' + CAST(HD_ID AS VARCHAR(4)), 3)) PERSISTED,
    DATLICHKHAM_ID INT,
    NGAYLAP DATE,
    TONGTIEN DECIMAL(18,2),
    HINHTHUCTHANHTOAN NVARCHAR(50),
    GHICHU NVARCHAR(200),
    CONSTRAINT FK_HOADON_DATLICH FOREIGN KEY (DATLICHKHAM_ID) REFERENCES DATLICHKHAM(DATLICHKHAM_ID) ON DELETE CASCADE
);

-- 9. Table CHITIETHOADON
CREATE TABLE CHITIETHOADON (
    CTHD_ID INT IDENTITY(1,1) PRIMARY KEY,
    HOADON_ID INT,
    DICHVU_ID INT,
    SOLUONG INT,
    THANHTIEN DECIMAL(18,2),
    CONSTRAINT FK_CTHD_HOADON FOREIGN KEY (HOADON_ID) REFERENCES HOADON(HD_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CTHD_DICHVU FOREIGN KEY (DICHVU_ID) REFERENCES DICHVU(DV_ID)
);

-- 10. Table KETQUAKHAM
CREATE TABLE KETQUAKHAM (
    KQ_ID INT IDENTITY(1,1) PRIMARY KEY,
    MAKQ AS ('KQ' + RIGHT('000' + CAST(KQ_ID AS VARCHAR(4)), 3)) PERSISTED,
    DATLICHKHAM_ID INT,
    CHUANDOAN NVARCHAR(300),
    KETLUAN NVARCHAR(300),
    THANHVIEN NVARCHAR(200),
    GHICHU NVARCHAR(200),
    CONSTRAINT FK_KQ_DATLICH FOREIGN KEY (DATLICHKHAM_ID) REFERENCES DATLICHKHAM(DATLICHKHAM_ID) ON DELETE CASCADE
);
GO

-- ==========================================
-- STORED PROCEDURES
-- ==========================================

-- SP thêm bệnh nhân mới
CREATE PROCEDURE PROC_ThemBenhNhan
    @HOTENBENHNHAN NVARCHAR(100),
    @CCCD VARCHAR(12),
    @SDT VARCHAR(15),
    @GIOITINH NVARCHAR(10),
    @BACSI_ID INT
AS
BEGIN
    INSERT INTO BENHNHAN(HOTENBENHNHAN, CCCD, SDT, GIOITINH, BACSI_ID)
    VALUES (@HOTENBENHNHAN, @CCCD, @SDT, @GIOITINH, @BACSI_ID)
END
GO

-- SP thống kê dịch vụ sử dụng nhiều nhất
CREATE PROCEDURE SP_DICHVUSUDUNGNHIEU
AS
BEGIN
    SELECT
        DV.DV_ID        AS MADV,
        DV.TENDV        AS TENDV,
        COUNT(CT.CTHD_ID)          AS SOLANSUDUNG,
        SUM(ISNULL(CT.SOLUONG, 0)) AS TONGSOLUONG
    FROM DICHVU DV
    LEFT JOIN CHITIETHOADON CT ON CT.DICHVU_ID = DV.DV_ID
    GROUP BY DV.DV_ID, DV.TENDV
    ORDER BY SOLANSUDUNG DESC
END
GO

-- ==========================================
-- FUNCTIONS
-- ==========================================

-- Tìm bác sĩ theo tên
CREATE FUNCTION TimBacSiTheoTen(@TEN NVARCHAR(100))
RETURNS TABLE
AS
RETURN (
    SELECT * FROM BACSI WHERE TENBACSI LIKE N'%' + @TEN + '%'
)
GO

-- Tìm kiếm khoa theo tên
CREATE FUNCTION FN_TimKiemKhoa(@TEN NVARCHAR(100))
RETURNS TABLE
AS
RETURN (
    SELECT * FROM KHOA WHERE TENKHOA LIKE N'%' + @TEN + '%'
)
GO

-- Xuất kết quả khám theo bệnh nhân (tra cứu bằng CCCD hoặc mã BN)
CREATE FUNCTION FN_XuatKetQuaDaKham_TheoBN(@MABN VARCHAR(5), @CCCD VARCHAR(12))
RETURNS TABLE
AS
RETURN (
    SELECT
        KQ.MAKQ,
        BN.MABENHNHAN,
        BN.HOTENBENHNHAN,
        BN.GIOITINH,
        BN.SDT,
        BS.MABACSI,
        BS.TENBACSI,
        K.TENKHOA,
        DL.NGAYKHAM,
        CK.GIOKHAM,
        KQ.CHUANDOAN,
        KQ.KETLUAN,
        KQ.THANHVIEN,
        KQ.GHICHU
    FROM KETQUAKHAM KQ
    JOIN DATLICHKHAM DL ON KQ.DATLICHKHAM_ID = DL.DATLICHKHAM_ID
    JOIN BENHNHAN BN     ON DL.BNHAN_ID       = BN.BNHAN_ID
    JOIN BACSI BS        ON DL.BACSI_ID        = BS.BACSI_ID
    LEFT JOIN KHOA K            ON BS.KHOA_ID   = K.KHOA_ID
    LEFT JOIN CAKHAM_MAPPING CK ON DL.CAKHAM_ID = CK.CAKHAM_ID
    WHERE (@MABN IS NULL OR BN.MABENHNHAN = @MABN)
      AND (@CCCD IS NULL OR BN.CCCD = @CCCD)
)
GO

-- ==========================================
-- DỮ LIỆU MẪU
-- ==========================================

-- Insert BENHVIEN
INSERT INTO BENHVIEN (TENBENHVIEN, SDT, DIACHI) VALUES
(N'Bệnh viện Tâm Anh', '02812345678', N'123 Đường Y Tế, Quận 1, TP. HCM');

-- Insert KHOA
INSERT INTO KHOA (TENKHOA, BENHVIEN_ID, SOBS) VALUES
(N'Khoa Nội',          1, 5),
(N'Khoa Ngoại',        1, 4),
(N'Khoa Nhi',          1, 3),
(N'Khoa Răng Hàm Mặt', 1, 2);

-- Insert BACSI
INSERT INTO BACSI (TENBACSI, GIOITINH, NAMSINH, KHOA_ID, SOBN, HOCHAM, HOCVI, CHUCVU, AVATAR) VALUES
(N'Nguyễn Văn A',  N'Nam', 1975, 1, 120, N'PGS', N'Bác sĩ CKII',     N'Trưởng khoa', '/images/bs1.jpg'),
(N'Trần Thị B',    N'Nữ',  1980, 2,  85, N'TS',  N'Bác sĩ Nội trú',  N'Phó khoa',    '/images/bs2.jpg'),
(N'Lê Minh C',     N'Nam', 1985, 3, 200, N'ThS', N'Bác sĩ CKI',      N'Bác sĩ',      '/images/bs3.jpg'),
(N'Phạm Quang D',  N'Nam', 1978, 4, 150, N'TS',  N'Bác sĩ CKII',     N'Trưởng khoa', '/images/bs4.jpg');

-- Insert CAKHAM_MAPPING
INSERT INTO CAKHAM_MAPPING (CAKHAM_ID, GIOKHAM) VALUES
(1, '07:30:00'),
(2, '08:30:00'),
(3, '09:30:00'),
(4, '10:30:00'),
(5, '13:30:00'),
(6, '14:30:00'),
(7, '15:30:00');

-- Insert BENHNHAN
INSERT INTO BENHNHAN (HOTENBENHNHAN, SDT, GIOITINH, BACSI_ID, AVATAR, CCCD) VALUES
(N'Hoàng Văn E',   '0912345678', N'Nam', 1, NULL, '001099123456'),
(N'Nguyễn Thị F',  '0987654321', N'Nữ',  1, NULL, '001099654321'),
(N'Trần Văn G',    '0901234567', N'Nam', 2, NULL, '001099111222'),
(N'Lê Thị H',      '0976543210', N'Nữ',  3, NULL, '001099333444');

-- Insert DICHVU
INSERT INTO DICHVU (TENDV, DONGIA, GHICHU, KHOA_ID) VALUES
(N'Khám nội tổng quát', 150000, N'Khám các bệnh lý nội khoa cơ bản', 1),
(N'Tiểu phẫu',          500000, N'Phẫu thuật nhỏ',                   2),
(N'Khám nhi tổng quát', 120000, N'Khám sức khoẻ trẻ em',             3),
(N'Nhổ răng khôn',      800000, N'Nhổ răng số 8',                    4);

-- Insert DATLICHKHAM (hôm nay + ngày mai)
INSERT INTO DATLICHKHAM (BNHAN_ID, BACSI_ID, NGAYKHAM, CAKHAM_ID, TRANGTHAI, THOIGIANDAT) VALUES
(1, 1, CAST(GETDATE() AS DATE),        2, N'Đã đặt',  GETDATE()),
(2, 1, CAST(GETDATE() AS DATE),        4, N'Đã đặt',  GETDATE()),
(3, 2, CAST(GETDATE() AS DATE),        3, N'Đã khám', GETDATE()),
(4, 3, CAST(DATEADD(DAY,1,GETDATE()) AS DATE), 1, N'Đã đặt',  GETDATE());

-- Insert HOADON
INSERT INTO HOADON (DATLICHKHAM_ID, NGAYLAP, TONGTIEN, HINHTHUCTHANHTOAN, GHICHU) VALUES
(3, CAST(GETDATE() AS DATE), 620000, N'Tiền mặt',    N'Đã thanh toán đủ'),
(1, CAST(GETDATE() AS DATE), 150000, N'Chuyển khoản', N'Chờ thanh toán');

-- Insert CHITIETHOADON
INSERT INTO CHITIETHOADON (HOADON_ID, DICHVU_ID, SOLUONG, THANHTIEN) VALUES
(1, 2, 1, 500000),
(1, 1, 1, 120000),
(2, 1, 1, 150000);

-- Insert KETQUAKHAM
INSERT INTO KETQUAKHAM (DATLICHKHAM_ID, CHUANDOAN, KETLUAN, THANHVIEN, GHICHU) VALUES
(3, N'Viêm ruột thừa cấp', N'Cần phẫu thuật cắt bỏ', N'Trần Thị B', N'Tiến hành tiểu phẫu ngay');
GO
