//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BACSI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BACSI()
        {
            this.BENHNHANs = new HashSet<BENHNHAN>();
            this.DATLICHKHAMs = new HashSet<DATLICHKHAM>();
        }
    
        public int BACSI_ID { get; set; }
        public string MABACSI { get; set; }
        public string TENBACSI { get; set; }
        public string GIOITINH { get; set; }
        public Nullable<int> NAMSINH { get; set; }
        public Nullable<int> KHOA_ID { get; set; }
        public Nullable<int> SOBN { get; set; }
        public string HOCHAM { get; set; }
        public string HOCVI { get; set; }
        public string CHUCVU { get; set; }
        public string AVATAR { get; set; }
    
        public virtual KHOA KHOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BENHNHAN> BENHNHANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATLICHKHAM> DATLICHKHAMs { get; set; }
    }
}
