//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENHNHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BENHNHAN()
        {
            this.DATLICHKHAMs = new HashSet<DATLICHKHAM>();
        }
    
        public int BNHAN_ID { get; set; }
        public string MABENHNHAN { get; set; }
        public string HOTENBENHNHAN { get; set; }
        public string SDT { get; set; }
        public string GIOITINH { get; set; }
        public Nullable<int> BACSI_ID { get; set; }
        public string AVATAR { get; set; }
        public string CCCD { get; set; }
    
        public virtual BACSI BACSI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATLICHKHAM> DATLICHKHAMs { get; set; }
    }
}
