//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATLICHKHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATLICHKHAM()
        {
            this.HOADONs = new HashSet<HOADON>();
            this.KETQUAKHAMs = new HashSet<KETQUAKHAM>();
        }
    
        public int DATLICHKHAM_ID { get; set; }
        public Nullable<int> BNHAN_ID { get; set; }
        public Nullable<int> BACSI_ID { get; set; }
        public Nullable<System.DateTime> NGAYKHAM { get; set; }
        public Nullable<int> CAKHAM_ID { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<System.DateTime> THOIGIANDAT { get; set; }
    
        public virtual BACSI BACSI { get; set; }
        public virtual BENHNHAN BENHNHAN { get; set; }
        public virtual CAKHAM_MAPPING CAKHAM_MAPPING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KETQUAKHAM> KETQUAKHAMs { get; set; }
    }
}
