//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUAKHAM
    {
        public int KQ_ID { get; set; }
        public string MAKQ { get; set; }
        public Nullable<int> DATLICHKHAM_ID { get; set; }
        public string CHUANDOAN { get; set; }
        public string KETLUAN { get; set; }
        public string THANHVIEN { get; set; }
        public string GHICHU { get; set; }
    
        public virtual DATLICHKHAM DATLICHKHAM { get; set; }
    }
}
